"use client";
import {useEffect,useState} from "react";

type Customer={id:string;name:string;phone:string;email?:string|null;planPrice:number;status:"ACTIVE"|"PAUSED"|"ENDED"};
const money=(n:number)=>`₹${n.toLocaleString("en-IN")}`;
export default function OwnerDashboard(){
 const [rows,setRows]=useState<Customer[]>([]),[stats,setStats]=useState({total:0,active:0,paused:0,ended:0}),[q,setQ]=useState(""),[status,setStatus]=useState("ALL"),[sort,setSort]=useState("name"),[order,setOrder]=useState("asc"),[page,setPage]=useState(1),[pages,setPages]=useState(1),[msg,setMsg]=useState(""),[bill,setBill]=useState<any>(null),[modal,setModal]=useState<"add"|"import"|"transfer"|null>(null),[selected,setSelected]=useState<Customer|null>(null),[form,setForm]=useState({name:"",phone:"",email:"",planPrice:"",startDate:""}),[csv,setCsv]=useState(""),[targetId,setTargetId]=useState(""),[transferDate,setTransferDate]=useState("");
 async function load(){const p=new URLSearchParams({q,status,sort,order,page:String(page),limit:"8"});const r=await fetch(`/api/customers?${p}`);if(r.status===401){location.href="/login";return}const d=await r.json();setRows(d.customers);setStats(d.stats);setPages(d.pagination.pages)}
 useEffect(()=>{load()},[q,status,sort,order,page]);
 async function add(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/subscriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,planPrice:Number(form.planPrice)})});const d=await r.json();if(!r.ok){setMsg(d.error);return}setMsg(`Subscription created for ${d.customer.name}. ${d.demoCustomerPassword?"Customer login password: demo1234":""}`);setModal(null);setForm({name:"",phone:"",email:"",planPrice:"",startDate:""});load()}
 async function act(c:Customer){const action=c.status==="ACTIVE"?"pause":"resume";const r=await fetch(`/api/subscriptions/${c.id}/${action}`,{method:"POST"});const d=await r.json();setMsg(r.ok?`${c.name} ${action}d.`:d.error);load()}
 async function showBill(c:Customer){const r=await fetch(`/api/bills/${c.id}?month=${new Date().toISOString().slice(0,7)}`);const d=await r.json();if(r.ok)setBill(d);else setMsg(d.error)}
 async function clock(){const date=new Date().toISOString().slice(0,10);const r=await fetch("/clock",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date})});const d=await r.json();setMsg(`Morning clock: ${d.created} notification(s) added to /outbox.`)}
 async function transfer(e:React.FormEvent){e.preventDefault();if(!selected)return;const r=await fetch(`/api/subscriptions/${selected.id}/transfer`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({toCustomerId:targetId,transferDate})});const d=await r.json();setMsg(r.ok?`Subscription transferred on ${d.transferDate}.`:d.error);setModal(null);load()}
 async function importCsv(){const r=await fetch("/api/import/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({csv})});const d=await r.json();if(!r.ok){setMsg(d.error);return}setMsg(`Import: ${d.imported} imported · ${d.deduped} deduped · ${d.rejected} rejected.`);setModal(null);load()}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/"}
 return <main><div className="container"><nav className="nav"><div className="logo">TiffinLedger</div><div className="actions"><button className="btn secondary small" onClick={clock}>Run morning clock</button><a className="btn secondary small" href="/outbox" target="_blank">View outbox</a><button className="btn secondary small" onClick={logout}>Logout</button></div></nav>
 <div className="head"><div><span className="eyebrow">Owner dashboard</span><h1>Customers & billing</h1></div><div className="actions"><button className="btn secondary" onClick={()=>setModal("import")}>Import CSV</button><button className="btn primary" onClick={()=>setModal("add")}>+ New subscription</button></div></div>
 {msg&&<div className="card toast">{msg}</div>}
 <div className="stats"><div className="card"><div className="statlabel">Customers</div><div className="statvalue">{stats.total}</div></div><div className="card"><div className="statlabel">Active</div><div className="statvalue">{stats.active}</div></div><div className="card"><div className="statlabel">Paused</div><div className="statvalue">{stats.paused}</div></div><div className="card"><div className="statlabel">Ended</div><div className="statvalue">{stats.ended}</div></div></div>
 <div className="toolbar"><input className="search" placeholder="Search name, phone or email…" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="PAUSED">Paused</option><option value="ENDED">Ended</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Sort: name</option><option value="planPrice">Sort: plan</option><option value="status">Sort: status</option><option value="createdAt">Sort: newest</option></select><button className="btn secondary small" onClick={()=>setOrder(order==="asc"?"desc":"asc")}>{order==="asc"?"↑ Asc":"↓ Desc"}</button></div>
 <div className="card table"><table><thead><tr><th>Customer</th><th>Phone</th><th>Plan</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><b>{c.name}</b><div className="muted" style={{fontSize:12}}>{c.email||"No customer account"}</div></td><td>{c.phone}</td><td>{money(c.planPrice)}/mo</td><td><span className={`pill ${c.status.toLowerCase()}`}>{c.status}</span></td><td><div className="actions"><button className="btn secondary small" onClick={()=>showBill(c)}>Bill</button>{c.status!=="ENDED"&&<button className="btn secondary small" onClick={()=>act(c)}>{c.status==="ACTIVE"?"Pause":"Resume"}</button>}{c.status!=="ENDED"&&<button className="btn secondary small" onClick={()=>{setSelected(c);setModal("transfer");setTransferDate(new Date().toISOString().slice(0,10))}}>Transfer</button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan={5}>No customers found.</td></tr>}</tbody></table><div className="head"><span className="muted">Page {page} of {pages}</span><div className="actions"><button className="btn secondary small" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="btn secondary small" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></div>
 {modal==="add"&&<div className="modalbg"><div className="card modal"><h2>New subscription</h2><form className="form" onSubmit={add}><label>Name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label>Phone</label><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><label>Customer email (optional account)</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><div className="two"><div><label>Monthly plan (₹)</label><input required type="number" min="1" value={form.planPrice} onChange={e=>setForm({...form,planPrice:e.target.value})}/></div><div><label>Cycle start</label><input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></div></div><div className="actions"><button className="btn primary">Create</button><button type="button" className="btn secondary" onClick={()=>setModal(null)}>Cancel</button></div></form></div></div>}
 {modal==="import"&&<div className="modalbg"><div className="card modal"><h2>Messy CSV import</h2><p className="muted">Columns: name, phone, planPrice, startDate. Supported dates include 2026-09-17, 2026/09/17, 17/09/2026 and 17-09-2026.</p><textarea rows={10} value={csv} onChange={e=>setCsv(e.target.value)} placeholder={'name,phone,planPrice,startDate\nRahul,9876543210,3000,01/09/2026\nRahul duplicate,9876543210,3000,2026-09-01\nPriya,,2800,15-09-2026'}/><div className="actions"><button className="btn primary" onClick={importCsv}>Import & report</button><button className="btn secondary" onClick={()=>setModal(null)}>Cancel</button></div></div></div>}
 {modal==="transfer"&&<div className="modalbg"><div className="card modal"><h2>Transfer subscription</h2><p className="muted">Current customer: <b>{selected?.name}</b>. The plan and cycle remain attached to the subscription; future/previous delivery history stays with the customer served.</p><form className="form" onSubmit={transfer}><label>Transfer to customer ID</label><input required placeholder="Paste target customer ID" value={targetId} onChange={e=>setTargetId(e.target.value)}/><label>Transfer date</label><input required type="date" value={transferDate} onChange={e=>setTransferDate(e.target.value)}/><div className="actions"><button className="btn primary">Transfer</button><button type="button" className="btn secondary" onClick={()=>setModal(null)}>Cancel</button></div></form></div></div>}
 {bill&&<div className="modalbg"><div className="card modal"><div className="head"><div><h2>{bill.customer.name}</h2><div className="muted">{bill.month} · {bill.customer.phone}</div></div><button className="btn secondary small" onClick={()=>setBill(null)}>Close</button></div><div className="muted">Month-end bill</div><div className="total">{money(bill.amount)}</div><div className="two" style={{marginTop:14}}><div className="card"><div className="muted">Plan</div><b>{money(bill.customer.planPrice)}</b></div><div className="card"><div className="muted">Daily rate</div><b>₹{bill.dailyRate.toFixed(2)}</b></div><div className="card"><div className="muted">Planned weekdays</div><b>{bill.plannedWeekdays}</b></div><div className="card"><div className="muted">Delivered</div><b>{bill.deliveredDays}</b></div></div><p className="muted">Formula: plan ÷ planned weekdays × actual served weekdays.</p></div></div>}
 </div></main>
}
